# Generated by Django 3.2 on 2021-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doners',
            name='blood_group',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='doners',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doners',
            name='negative_tested_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
