# Generated by Django 3.2 on 2021-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20210426_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('negative_tested_on', models.DateField(null=True)),
                ('cronic_illness', models.BooleanField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doners',
        ),
    ]
