# Generated by Django 3.2 on 2021-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_donorsinfo_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorsinfo',
            name='cronic_illness',
        ),
        migrations.AddField(
            model_name='donorsinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=12, null=True),
        ),
    ]
