# Generated by Django 3.2 on 2021-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20210503_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorsinfo',
            name='donate_center',
            field=models.CharField(choices=[('1', 'Donation center 1'), ('2', 'Donation center 2'), ('3', 'Donation center 3')], default='1', max_length=12),
        ),
        migrations.AlterField(
            model_name='donorsinfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorsinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=12),
        ),
    ]
