# Generated by Django 3.2 on 2021-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20210504_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorsinfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donorsinfo',
            name='donate_center',
            field=models.CharField(choices=[('1', 'Donation center 1'), ('2', 'Donation center 2'), ('3', 'Donation center 3')], default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='donorsinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=12),
        ),
    ]
