# Generated by Django 3.2 on 2021-05-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_auto_20210504_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiverInfo',
        ),
    ]
